# Generated by Django 2.1.3 on 2018-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trips", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="car",
            name="price_per_trip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
