# Generated by Django 2.1.3 on 2018-11-10 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2048)),
                ("price_per_trip", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "way",
                    models.CharField(
                        choices=[("go_to", "Ida"), ("return", "Vuelta")],
                        default="go_to",
                        max_length=8,
                    ),
                ),
                (
                    "price_per_passenger",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("notes", models.CharField(max_length=2048)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="trips.Car",
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        related_name="trips", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
