# Generated by Django 2.1.3 on 2018-11-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20181110_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_trip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_passenger',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
