# Generated by Django 2.2.6 on 2020-03-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20181111_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('date', 'car', 'way')},
        ),
    ]
